import 'dart:developer' as developer;
import 'dart:io';

import 'package:firebase_auth/firebase_auth.dart' as fba;
import 'package:google_sign_in/google_sign_in.dart' as gsi;
import 'package:myapp/services/storage_service.dart';

class AuthService {
  final fba.FirebaseAuth _auth = fba.FirebaseAuth.instance;
    final gsi.GoogleSignIn _googleSignIn = gsi.GoogleSignIn();
      final StorageService _storageService = StorageService();

        Future<fba.UserCredential?> signInWithGoogle() async {
            try {
                  final gsi.GoogleSignInAccount? googleUser = await _googleSignIn.signIn();

                        if (googleUser == null) {
                                developer.log('Google Sign-In aborted by user.', name: 'AuthService');
                                        return null;
                                              }

                                                    final gsi.GoogleSignInAuthentication googleAuth =
                                                              googleUser.authentication;

                                                                    final fba.AuthCredential credential = fba.GoogleAuthProvider.credential(
                                                                            accessToken: googleAuth.accessToken,
                                                                                    idToken: googleAuth.idToken,
                                                                                          );

                                                                                                return await _auth.signInWithCredential(credential);
                                                                                                    } catch (e, s) {
                                                                                                          developer.log(
                                                                                                                  'Failed to sign in with Google',
                                                                                                                          name: 'AuthService',
                                                                                                                                  error: e,
                                                                                                                                          stackTrace: s,
                                                                                                                                                );
                                                                                                                                                      return null;
                                                                                                                                                          }
                                                                                                                                                            }

                                                                                                                                                              Future<void> signOut() async {
                                                                                                                                                                  try {
                                                                                                                                                                        await _googleSignIn.signOut();
                                                                                                                                                                              await _auth.signOut();
                                                                                                                                                                                  } catch (e, s) {
                                                                                                                                                                                        developer.log(
                                                                                                                                                                                                'Error signing out',
                                                                                                                                                                                                        name: 'AuthService',
                                                                                                                                                                                                                error: e,
                                                                                                                                                                                                                        stackTrace: s,
                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                      fba.User? getCurrentUser() {
                                                                                                                                                                                                                                          return _auth.currentUser;
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                              Stream<fba.User?> get authStateChanges => _auth.authStateChanges();

                                                                                                                                                                                                                                                Future<void> updateProfile(String displayName) async {
                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                          final user = _auth.currentUser;
                                                                                                                                                                                                                                                                if (user != null) {
                                                                                                                                                                                                                                                                        await user.updateDisplayName(displayName);
                                                                                                                                                                                                                                                                                await user.reload();
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                          } catch (e, s) {
                                                                                                                                                                                                                                                                                                developer.log(
                                                                                                                                                                                                                                                                                                        'Error updating profile',
                                                                                                                                                                                                                                                                                                                name: 'AuthService',
                                                                                                                                                                                                                                                                                                                        error: e,
                                                                                                                                                                                                                                                                                                                                stackTrace: s,
                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                            rethrow;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                    Future<void> updatePhotoURL(String photoURL) async {
                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                              final user = _auth.currentUser;
                                                                                                                                                                                                                                                                                                                                                                    if (user != null) {
                                                                                                                                                                                                                                                                                                                                                                            await user.updatePhotoURL(photoURL);
                                                                                                                                                                                                                                                                                                                                                                                    await user.reload();
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                              } catch (e, s) {
                                                                                                                                                                                                                                                                                                                                                                                                    developer.log(
                                                                                                                                                                                                                                                                                                                                                                                                            'Error updating photo URL',
                                                                                                                                                                                                                                                                                                                                                                                                                    name: 'AuthService',
                                                                                                                                                                                                                                                                                                                                                                                                                            error: e,
                                                                                                                                                                                                                                                                                                                                                                                                                                    stackTrace: s,
                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                rethrow;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        Future<void> uploadProfilePicture(File image) async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  final user = _auth.currentUser;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (user != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                final photoURL =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await _storageService.uploadProfilePicture(user.uid, image);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await updatePhotoURL(photoURL);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (e, s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    developer.log(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Error uploading profile picture',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name: 'AuthService',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            error: e,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stackTrace: s,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rethrow;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      